import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const harmonyOS = localFont({
  src: [
    {
      path: "./fonts/HarmonyOS_Sans_Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Regular_Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Medium_Italic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Bold_Italic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Light_Italic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HarmonyOS_Sans_Thin_Italic.ttf",
      weight: "100",
      style: "italic",
    },
  ],
  variable: "--font-harmony",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${harmonyOS.variable} font-harmony antialiased`}>
        {children}
      </body>
    </html>
  );
}
